package Utilities.ItemUtilities;


import Utilities.Utilities;

/**
 * Created by broskj on 3/5/16.
 */
public enum ItemsEnum {
    HEALTH_POTION, MANA_POTION, STRENGTH_POTION, AGILITY_POTION, INTELLECT_POTION, HARDINESS_POTION, EXPERIENCE_POTION,
        MOVEMENT_POTION, STICK_SWORD, STICK_GREATSWORD, SWORDFISH_DAGGER, SWORDFISH_LANCE, PUFFER_FISH_MACE,
        PUFFER_FISH_FLAIL, MOUSE_ON_A_STRING_WAND, CATNIP_STAFF, HAIRBALL, LASER_POINTER, FISH_BOOMERANG, CHEST_KEY,
        OPEN_TREASURE_CHEST, CLOSED_TREASURE_CHEST, DOOR_KEY, OPEN_DOOR, CLOSED_DOOR, HELMET, CHESTPLATE, PLATELEGS,
        GAUNTLETS, BOOTS, SHIELD, MILDLY_COOL_RING, DOPE_RING, PANTS
}
