package Utilities.ItemUtilities;


/**
 * Created by broskj on 3/5/16.
 */
public enum ItemsEnum {
        BAGOFITEMS, HEALTH_POTION, MANA_POTION, STRENGTH_POTION, AGILITY_POTION, INTELLECT_POTION, HARDINESS_POTION,
        EXPERIENCE_POTION, MOVEMENT_POTION, STICK_SWORD, STICK_GREATSWORD, SWORDFISH_DAGGER, SWORDFISH_LANCE,
        PUFFER_FISH_FLAIL, MOUSE_ON_A_STRING_WAND, CATNIP_STAFF, LASER_POINTER, FISH_BOOMERANG, CHEST_KEY,
        CLOSED_TREASURE_CHEST, OPEN_TREASURE_CHEST, DOOR_KEY, OPEN_DOOR, CLOSED_DOOR, HELMET, CHESTPLATE, PLATELEGS,
        GAUNTLETS, BOOTS, SHIELD, MILDLY_COOL_RING, DOPE_RING, PANTS, HOUSE, SMALL_COIN_STACK, MEDIUM_COIN_STACK,
        LARGE_COIN_STACK, TUNA, SUSHI, PUFFER_FISH_MACE, VERT_FENCE, HORIZ_FENCE_ODD, HORIZ_FENCE_EVEN, WOODEN_DOOR
}
